services:
  server:
    build:
      context: ./server
    container_name: fileserver
    environment:
      - HOST=0.0.0.0         
      - PORT=5000
      - FILES_DIR=/data
      - MAX_UPLOAD_BYTES=5505024
    volumes:
      - ./data:/data          
    ports:
      - "5000:5000" 
   

  client:
    build:
      context: ./client
    container_name: fileclient
    stdin_open: true
    tty: true
    depends_on:
      - server
