services:
  server:
    build:
      context: ./server
    container_name: fileserver
    environment:
      - HOST=0.0.0.0         
      - PORT=5000
      - FILES_DIR=/data
      - MAX_UPLOAD_BYTES=5505024
    volumes:
      - ./data:/data          
    ports:
      - "5000:5000" 
    healthcheck:
      test: ["CMD-SHELL", "python -c 'import socket; s=socket.socket(); s.settimeout(1); s.connect((\"127.0.0.1\", 5000)); print(\"ok\")'"]
      interval: 10s
      timeout: 3s
      retries: 5

  client:
    build:
      context: ./client
    container_name: fileclient
    stdin_open: true
    tty: true
    depends_on:
      server:
        condition: service_healthy
